### PR TITLE
Fix network buttons styles

### PR DESCRIPTION
**Pull request by nightsh**

### CODE REVIEW

**Comment by chutko** [comment]
its due to general styles i created for the buttons. i plan to fix it soon

**Comment by nightsh** [comment]
It's not only that, but a recent migration towards the `npm` package for `vis`, instead of `bower` broke a few requests. So what I had to do was to publish some assets. I also did a small `vis-button` mixin for all the buttons to be shown on the network.

**Comment by chutko** [comment]
okay, i will have look at them

**Comment by chutko** [comment]
i have cleaned up and simplified the styles for `.vis-navigation` buttons. used our scss variables and mixins. also moved this component styles into separate file `vis/navigation.scss` and as we go, we could create completely our own styles for vis.js separated into few subcomponents so we do not need default vis.js styles at all. 

anyway, there are still things i would like to solve in this issue:

1. why/how is vendor.css included after our styles? that means default vendor.css styles rewrite our own .scss which is ridiculous - then we have to use !important everywhere and everything gets more complicated. can it be included in reverse order?

2. the buttons on the right side of the network are contained in 2 separate elements:
`#network-controls` - contains share button and settings button 
`.vis-navigation` - contains all else
is it possible to put these buttons under one element? maybe there is a vis.js function to add a network control button. or something simple like `$(element).append` could do the job

3. there are few buttons in the code which we will most likely not use at all: 
`.vis-button.vis-up`, 
`.vis-button.vis-down`, 
`.vis-button.vis-left`, 
`.vis-button.vis-right`
can they be easily removed in vis.js options or do they have to be there? i know its not a big thing, but if we will make compromises like this everywhere, the code gets bigger and the app gets slower.

**Comment by chutko** [comment]
pushed into branch `fix/network-icons2`
needs fixing some of the above mentioned, doesnt look good yet

**Pull request merged**
