### PR TITLE
[#117] Fix missing link to CPV definition

### PR DESCRIPTION
**Pull request by nightsh**
Goes to https://simap.ted.europa.eu/cpv

### CODE REVIEW

**Comment by nightsh** [comment]
It's not deployed (yet). After the merge. Just checking if the link above is the right one.

Thinking about it, it'd probably be nice to automatically deploy the PRs somewhere temporary. Will have a look at it.

**Comment by zufanka** [comment]
oh! yes that is the link :)

**Comment by nightsh** [comment]
Approve the PR then! Thought it would be an easy one to get you into the loop with github workflows, it might be needed again in the future :)

**Comment by zufanka** [comment]
like this?

**Comment by nightsh** [comment]
Yup. Approval is usually enough, as the author might want to squash their commits before merging. So no need to merge, just the seal of approval would do :)

Alright, once we have the automated deployment, maybe merging would also make sense. We'll see when we get there, but it didn't cross my mind until now.

**Comment by zufanka** [comment]
I didn't know where to click!
omg :)
ok gimme another one later, I will excercise this!

**Pull request merged**
